Python 3:
  script:
  - py_version=3
  - EXTRA_INSTALL="numpy scipy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Documentation:
  script:
  - EXTRA_INSTALL="numpy scipy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - . ./prepare-and-run-flake8.sh "$CI_PROJECT_NAME" examples test
  tags:
  - python3
  except:
  - tags
